parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Vin\ShopwareSdkEntityGenerator\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
